name: ecu300zx

services:

  ecu300zx_container:
    container_name: ecu300zx_container
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    privileged: true
    ports:
      - "8088:80"
      - "8087:8080"
    networks:
      - ecu300zx-network
    volumes:
     - ./../../app/frontend/:/var/www/frontend
     - ./../../app/backend/:/var/www/backend
    environment:
      - megaraid_wrapper_from=file
      - checksatadevices=true
      - noauthentication=true
   
networks:
  ecu300zx-network:
    name: ecu300zx-network
    driver: bridge